version: '3.8'

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      target: runner  
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - BE-network
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DJANGO_SETTINGS_MODULE=planner.settings
      - DJANGO_DEBUG=False  # DEBUG to False for production
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=prod
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=planner-db
      - POSTGRES_PORT=5432
    networks:
      - BE-network
    depends_on:
      - planner-db
      
  planner-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER=prod
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432"
    networks:
      - BE-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  BE-network:
    driver: bridge

volumes:
  pgdata:
