name: 'planner-prod'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - planner-network
    depends_on:
      - frontend
      - backend

  frontend:
    restart: always
    build:
      context: ./frontend
      target: prod-runner  
      args:
        NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID}
    env_file:
      - ./env/prod/frontend.env
    depends_on:
      - backend
    networks:
      - planner-network
  
  backend:
    build: ./backend
    command: sh /app/entrypoint_prod.sh
    env_file:
      - ./env/prod/backend.env
      - ./env/prod/db.env
    networks:
      - planner-network
    depends_on:
      - planner-db
      
  planner-db:
    image: postgres:latest
    restart: always
    env_file:
      - ./env/prod/db.env
    networks:
      - planner-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  planner-network:
    driver: bridge

volumes:
  pgdata:
