version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DJANGO_SETTINGS_MODULE=planner.settings
      - DJANGO_DEBUG=False  # DEBUG to False for production
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=planner
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
      
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=planner
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
