# Generated by Django 5.0.8 on 2024-10-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawcourse',
            name='course_component_code',
        ),
        migrations.AddField(
            model_name='rawcourse',
            name='associated_academic_career',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='rawcourse',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rawcourse',
            name='requirements_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rawcourse',
            name='term_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
